var ecampusServices = angular.module('ecampus.services', ['ngCookies']);

ecampusServices.factory('API', ['$rootScope', function ($rootScope) {
    $rootScope.csv_url = view_url;
    $rootScope.base_url = view_url;
    $rootScope.attechment_url = view_url + 'storage/attachment/';
    $rootScope.company_imag_url = view_url + 'storage/feed-images/';
    $rootScope.grievace_url = view_url + 'storage/grievance_attachment/';
    $rootScope.request_att_url = view_url + 'storage/attendance-attachments/';
    $rootScope.attendance_attechment_url = view_url + 'storage/attendance-attachments/';
    $rootScope.web_url = window.location.protocol + '//' + window.location.hostname + '/ecampus/';
    $rootScope.social_url = social_url;

    return {
        auth_state: base_url + 'verify-state-auth',
        user_login: base_url + 'login',
        user_types: base_url + 'get-account-types', //Only used in user types services to get all types
        get_departments: base_url + 'get-departments',
        add_hod: base_url + 'add-hod',
        get_hods: base_url + 'get-hods',
        add_teacher: base_url + 'add-teacher',
        get_hod_teachers: base_url + 'get-hod-teachers',
        get_teachers: base_url + 'get-teachers',
        add_student: base_url + 'add-student',
        get_user_profile: base_url + 'profile',
        get_department_teachers: base_url + 'get-teachers',
        get_department_subject: base_url + 'get-subjects',
        create_time_table: base_url + 'timetable',
        get_branches: base_url + 'get-branches',
        get_week_days: base_url + 'get-timetable',
        edit_time_table: base_url + 'update-timetable',
        delete_time_table: base_url + 'delete-timetable',
        get_student: base_url + 'get-lecture-students-list ',
        take_attendence: base_url + 'set-student-attendance',
        edit_profile: base_url + 'update-profile',
        post_news_feed: base_url + 'post-news-feed',
        upload_neswfeed_image: base_url + 'upload-feed-image',
        upload_newsfeed_attechedment: base_url + 'upload-feed-attachments',
        get_moderator: base_url + 'get-feed-moderators',
        get_attendence: base_url + 'get-student-attendance',
        approved_posts: base_url + 'approve-feed',
        declined_posts: base_url + 'decline-feed',
        get_news_feed: base_url + 'get-news-feeds',
        archived_post: base_url + 'archive-feed',
        get_unapproved_post: base_url + 'get-unapproved-post',
        post_action_admin: base_url + 'post-action-admin',
        post_delete_admin: base_url + 'post-delete-admin',
        delete_feeds_file: base_url + 'delete-feeds-file',
        get_all_feeds: base_url + 'get-feeds',
        get_own_post: base_url + 'get-user-feeds',
        add_comments_on_post: base_url + 'post-news-feed-comment',
        get_recenet_attendence: base_url + 'get-recent-attendance',
        get_lecture_attendance: base_url + 'get-lecture-attendance',
        upload_csv: base_url + 'upload-csv',
        upload_mst_result: base_url + 'upload-result-mst',
        get_mst_result: base_url + 'get-mst-result',
        get_mst_result_marks: base_url + 'get-mst-result-marks',
        get_student_mst_result: base_url + 'get-student-mst-result',
        upload_sessional_result: base_url + 'upload-result-sessional',
        get_sessional_result: base_url + 'get-sessional-result',
        get_sessional_result_marks: base_url + 'get-sessional-result-marks',
        upload_semester_result: base_url + 'upload-result-semester',
        get_semester_result: base_url + 'get-semester-result',
        get_semester_result_marks: base_url + 'get-semester-result-marks',
        upload_semester_grade_result: base_url + 'upload-grades-semester',
        get_smester_grades_result: base_url + 'get-semester-grades',
        get_semester_grade_result_marks: base_url + 'get-semester-grades-details',
        get_users: base_url + 'get-message-users',
        send_message: base_url + 'send-message',
        add_msg_attachment: base_url + 'add-attachment',
        get_inbox_msg: base_url + 'get-inbox',
        get_sent_msg: base_url + 'get-sentbox',
        get_inbox_msg_detail: base_url + 'sub-inbox',
        draft_msg: base_url + 'msg-drafts',
        get_draft_msg: base_url + 'get-draft-msg',
        started_msg: base_url + 'mark-message-star',
        get_draft_threads: base_url + 'get-drafts-messages',
        get_notifications: base_url + 'get-notifications',
        reset_notifications: base_url + 'reset-notifications',
        get_started_msg: base_url + 'get-starred-messages',
        delete_inbox_msg: base_url + 'delete-inbox-msg',
        delete_sent_msg: base_url + 'delete-sent-msg',
        delete_draft_msg: base_url + 'delete-draft-msg',
        upload_profile_picture: base_url + 'upload-profile-picture',
        create_lable: base_url + 'create-label',
        get_lable: base_url + 'get-lable',
        add_into_label: base_url + 'add-label-data',
        get_data_into_label: base_url + 'get-label-messages',
        delete_label_name: base_url + 'delete-label',
        delete_label_msg: base_url + 'delete-label-data',
        all_type_roles: base_url + 'all-type-roles',
        apply_roles: base_url + 'apply-roles',
        user_roles: base_url + 'user-roles',
        delete_sub_inbox_msg: base_url + 'delete-sub-inbox-msg',
        add_accounts: base_url + 'add-account',
        get_branch_student: base_url + 'get-branch-student',
        get_all_department_mentors: base_url + 'all-department-mentor',
        mentor_details: base_url + 'mentor-details',
        add_mentor_type: base_url + 'add-mentor',
        assign_students: base_url + 'add-mentee',
        add_new_label: base_url + 'add-new-label',
        get_hod_timetable: base_url + 'get-own-timetable',
        upload_attendance_csv: base_url + 'upload-attendance-csv',
        submit_att_csv: base_url + 'set-attendance-csv',
        get_teacher_request: base_url + 'get-csv-request',
        action_on_teacherRequest: base_url + 'csv-request-action',
        get_teacherRequest_detail: base_url + 'single-csv-request',
        create_ques_from: base_url + 'add-mentorship-form',
        get_ques_form: base_url + 'get-mentorship-forms',
        create_mentor_ques: base_url + 'add-mentorship-question',
        get_mentor_ques_frm: base_url + 'get-form-questions',
        get_form_ques: base_url + 'get-feedbackform-questions',
        get_mentee: base_url + 'get-mentee',
        approve_mst_result: base_url + 'approve-mst-marks',
        get_mentor_ques_form: base_url + 'get-mentor-form',
        approve_semester_grades: base_url + 'approve-semester-grades',
        approve_sessional_result: base_url + 'approve-sessional-result',
        submit_counselling_form: base_url + 'submit-counselling-form',
        add_new_ques: base_url + 'add-new-question',
        get_previous_conselling: base_url + 'get-counselling',
        get_single_counselling: base_url + 'get-single-counselling',
        get_own_counselling: base_url + 'get-own-counselling',
        get_all_our_user: base_url + 'get-all-users',
        single_user_permission: base_url + 'get-user-access-list',
        give_access: base_url + 'grant-access',
        remove_access: base_url + 'remove-access',
        count_of_unreadMsg: base_url + 'unread-message-count',
        get_account_type: base_url + 'get-count-type',
        get_sent_msg_detail: base_url + 'get-single-sent-msg-detail',
        get_star_msg_detail: base_url + 'get-single-star-msg-detail',
        get_draft_msg_detail: base_url + 'get-single-draft-msg-detail',
        get_branch_mentee: base_url + 'get-branch-all-student',
        get_single_mentee_couns: base_url + 'get-single-student-counselling',
        get_student_all_details: base_url + 'get-student-details',
        delete_own_post: base_url + 'delete-feed',
        get_user_types: base_url + 'get-user-type',
        get_all_branch_students: base_url + 'get-all-students',
        get_all_students_elective: base_url + 'get-all-students-elective',
        view_user_profile_info: base_url + 'get-user-profile',
        view_child_profile_info: base_url + 'get-child-profile',
        view_user_profile_posts: base_url + 'get-user-feeds',
        view_child_profile_posts: base_url + 'get-child-feeds',
        verify_education: base_url + 'education-verify',
        add_suggetion: base_url + 'post-suggestion',
        get_suggetion: base_url + 'get-suggestions',
        change_password: base_url + 'change-password',
        get_single_suggetion: base_url + 'get-single-suggestion',
        set_counselling_dates: base_url + 'add-counseling-dates',
        set_counselling_schedule: base_url + 'add-counseling-schedule',
        get_counseling_date: base_url + 'get-counseling-date',
        get_assigned_mentors: base_url + 'get-mentors',
        view_counselling_duration: base_url + 'student-schedule',
        add_new_company: base_url + 'add-new-company',
        get_companies: base_url + 'get-companies',
        get_single_comapany: base_url + 'get-company-details',
        approve_company: base_url + 'approve-company',
        reject_company: base_url + 'reject-company',
        activate_company: base_url + 'activate-company',
        delete_company: base_url + 'delete-company',
        add_new_consultancy: base_url + 'add-new-consultancy',
        get_consultancies: base_url + 'get-consultancies',
        get_singel_consultancy: base_url + 'get-consultancy-details',
        add_Student_basic_info: base_url + 'update-family-info',
        add_placement_circular: base_url + 'add-circular',
        add_eligibility_criteria: base_url + 'add-circular-eligibility',
        add_feedback_form: base_url + 'add-feedback-form',
        get_feedback_form: base_url + 'get-feedback-form',
        get_form_questions: base_url + 'get-form-questions',
        get_feedback_batches: base_url + 'get-feedback-batches',
        send_feedback: base_url + 'ask-feedback',
        get_feedbacks: base_url + 'get-ask-feedback',
        get_single_feedback: base_url + 'get-single-feedback',
        edit_feedback: base_url + 'edit-ask-feedback',
        get_feedback_to_student: base_url + 'get-student-feedback',
        get_student_feedback_question: base_url + 'selected-feedback-questions',
        give_feedback: base_url + 'give-feedback',
        feedback_selected_batches: base_url + 'feedback-selected-batches',
        feedback_report: base_url + 'feedback-report',
        add_achievement: base_url + 'add-achievement',
        upload_achievement_attachment: base_url + 'upload-achievement-attachment',
        edit_achievement: base_url + 'edit-achievement',
        get_achievement: base_url + 'get-achievement',
        add_subject_faculty: base_url + 'add-subject-faculty',
        change_subject_status: base_url + 'change-subject-status',
        get_subject_faculties: base_url + 'get-subject-faculties',
        placement_circular_list: base_url + 'get-placement-circular',
        single_placement_circular: base_url + 'get-placement-circular-details',
        get_tnp_news: base_url + 'get-tnp-news',
        change_circular_status: base_url + 'change-circular-status',
        add_session: base_url + 'add-session',
        get_session: base_url + 'get-sessions',
        add_holiday: base_url + 'add-holiday',
        get_holidays: base_url + 'get-holidays',
        create_Student_time_table: base_url + 'create-time-table',
        get_time_table_sessions: base_url + 'time-table-sessions',
        get_time_table: base_url + 'get-time-table',
        copy_time_table: base_url + 'copy-time-table',
        get_subject_lecture: base_url + 'get-subject-lectures',
        edit_subject_lecture: base_url + 'edit-subject-lectures',
        add_break: base_url + 'add-break',
        raise_attendance: base_url + 'raise-attendance',
        get_all_faculties: base_url + 'get-all-faculties',
        get_attendance_requests: base_url + 'get-attendance-request',
        action_attendance_request: base_url + 'action-attendance-request',
        get_master_timetable: base_url + 'get-master-timetable',
        assign_hod_department: base_url + 'assign-hod-department',
        remove_hod: base_url + 'remove-user-department',
        remove_session: base_url + 'remove-session',
        add_subject: base_url + 'add-subject',
        get_all_teacher: base_url + 'get-all-teachers',
        get_day_lecture: base_url + 'get-day-lecture',
        // delete_time_table:base_url + 'delete-timetable',
        change_time_table: base_url + 'change-timetable',
        edit_subject: base_url + 'edit-subject',
        get_student_form: base_url + 'get-profile',
        get_faculty_subjects: base_url + 'get-faculty-subjects',
        update_current_education: base_url + 'update-current-education', //mentoring APIs
        assigned_faculties: base_url + 'assigned-faculties',
        get_senior_mentor: base_url + 'get-senior-mentor',
        get_junior_mentor: base_url + 'get-not-assigned-mentor',
        add_junior_mentor: base_url + 'assign-junior-mentor',
        get_assign_junior_mentor: base_url + 'get-assign-mentor',
        remove_assign_junior_mentor: base_url + 'remove-assign-mentor',
        delete_counseling_forms: base_url + 'delete-mentorship-form',
        delete_mentorship_forms_ques: base_url + 'delete-mentorship-question',
        edit_mentorship_form: base_url + 'edit-mentorship-form',
        edit_mentorship_question: base_url + 'edit-mentorship-question',
        get_counseling_duration: base_url + 'get-all-counseling-date',
        add_student_batch: base_url + 'edit-current-education',
        get_lab_batches: base_url + 'get-batches',
        get_pending_attendance: base_url + 'get-pending-attendance',
        upload_pending_attendance: base_url + 'upload-pending-attendance',
        search_on_message: base_url + 'message-search',
        apply_for_forget_password: base_url + 'forgot-password',
        forget_password_submit: base_url + 'update-forget-password',
        active_or_deactive_users: base_url + 'change-status',
        reset_admin_password: base_url + 'reset-user-password',
        update_account_informations: base_url + 'edit-user-profile',
        logout: base_url + 'logout',
        get_server_date: base_url + 'get-server-date',
        get_today_lecture: base_url + 'get-your-lecture',
        get_all_message_groups: base_url + 'get-all-groups',
        single_message_group: base_url + 'get-single-group-details',
        edit_message_group: base_url + 'edit-default-group',
        add_new_message_group: base_url + 'create-new-group',
        get_member_list: base_url + 'get-custom-group-details',
        add_new_member: base_url + 'add-new-member',
        search_member: base_url + 'search-member',
        get_all_user_groups: base_url + 'get-all-user-groups',
        edit_single_lecture: base_url + 'change-single-lecture',
        get_school_boards: base_url + 'get-school-boards',
        filter_eligible_students: base_url + 'filter-eligible-students',

        add_education_pofile: base_url + 'add-education-profile', //mentoring APIs
        add_student_education: base_url + 'add-student-education', //mentoring APIs
        delete_student_education: base_url + 'delete-student-education', //mentoring APIs
        add_semester_detail: base_url + 'add-semester-detail', //mentoring APIs
        add_academic_attendance: base_url + 'add-academic-attendance', //mentoring APIs
        add_training_attendance: base_url + 'add-training-attendance', //mentoring APIs
        add_training_detail: base_url + 'add-training-detail', //mentoring APIs
        add_placement_detail: base_url + 'add-placement-detail', //mentoring APIs
        add_job_profile: base_url + 'add-job-profile', //mentoring APIs

        update_social_profile: base_url + 'update-social-profile', //mentoring APIs
        update_education_pofile: base_url + 'update-education-profile', //mentoring APIs

        get_social_profile: base_url + 'get-social-profile', //mentoring APIs
        get_education_pofile: base_url + 'get-education-profile', //mentoring APIs
        get_semester_detail: base_url + 'get-semester-detail', //mentoring APIs
        get_academic_attendance: base_url + 'get-academic-attendance', //mentoring APIs
        get_training_attendance: base_url + 'get-training-attendance', //mentoring APIs
        get_training_detail: base_url + 'get-training-detail', //mentoring APIs
        get_placement_detail: base_url + 'get-placement-detail', //mentoring APIs
        get_job_profile: base_url + 'get-job-profile', //mentoring APIs

        verify_semester_detail: base_url + 'verify-semester-detail', //mentoring APIs
        verify_academic_attendance: base_url + 'verify-academic-attendance', //mentoring APIs
        verify_training_attendance: base_url + 'verify-training-attendance', //mentoring APIs
        verify_training_detail: base_url + 'verify-training-detail', //mentoring APIs
        verify_placement_detail: base_url + 'verify-placement-detail', //mentoring APIs
        verify_student_achievement: base_url + 'verify-student-achievement', //mentoring APIs

        remove_training_detail: base_url + 'remove-training-detail', //mentoring APIs
        delete_education_pofile: base_url + 'delete-education-profile', //mentoring APIs

        get_student_achievements: base_url + 'get-student-achievements', //mentoring APIs
        add_student_achievement: base_url + 'add-student-achievement', //mentoring APIs
        edit_student_achievement: base_url + 'edit-student-achievement', //mentoring APIs

        remove_group_member: base_url + 'remove-group-member',
        compose_message: base_url + 'compose-message',
        get_single_message: base_url + 'get-single-message',
        delete_message: base_url + 'delete-message',
        move_message: base_url + 'move-message',
        move_into_inbox: base_url + 'move-to-inbox',
        edit_consultancy: base_url + 'edit-consultancy',
        edit_circular: base_url + 'edit-circular',
        edit_circular_eligibility: base_url + 'edit-circular-eligibility',
        edit_company: base_url + 'edit-company-details',
        get_account_groups: base_url + 'get-account-groups',
        create_default_group: base_url + 'create-default-group',
        move_user_group: base_url + 'move-user-group',
        get_circular_eligibility: base_url + 'get-eligibility',
        activate_consultancy: base_url + 'activate-consultancy',
        delete_consultancy: base_url + 'delete-consultancy',
        get_follow_ups: base_url + 'get-followups',
        addcomment_followups: base_url + 'addcomment-followups',
        generate_feedback_reports: base_url + 'save-feedback',
        single_faculty_feedback: base_url + 'single-faculty-feedback',
        get_my_feedback: base_url + 'get-my-feedback',
        get_interview_rounds: base_url + 'get-interview-rounds',
        get_campus_day_list: base_url + 'get-campus-day-list',
        update_campus_day_details: base_url + 'update-campus-day-details',
        close_campus: base_url + 'close-placement',
        get_placement_reports: base_url + 'get-placement-reports',
        remove_mentee: base_url + 'remove-assign-mentor',
        get_faculty_subject: base_url + 'get-subjects-results',
        edit_label_name: base_url + 'rename-label',
        send_campus_news: base_url + 'publish-newsfeed',
        check_eligibility: base_url + 'check-eligibility',
        submit_interest: base_url + 'submit-interest',
        get_company_drive_reports: base_url + 'get-company-drive-reports',
        get_branch_batch_reports: base_url + 'get-placement-reports',
        get_placed_student_report: base_url + 'get-placed-students-report',
        get_individual_report: base_url + 'get-individual-student-report',
        get_branchwise_individual_report: base_url + 'get-branch-students-report',
        send_message_to_candidates: base_url + 'send-message-campus-round',
        check_selection: base_url + 'check-selection',
        submit_joining_confirmation: base_url + 'submit-joining',
        previous_conseling_dates: base_url + 'get-mentoring-durations',
        get_mentor_report_list: base_url + 'get-mentors-report-list',
        get_single_mentor_report: base_url + 'get-single-mentor-report',
        list_of_eligible_stuidents: base_url + 'get-eligible-student-list',
        add_student_in_campus: base_url + 'add-new-eligible-student',
        ativate_deactive_campus: base_url + 'deactivate-circular',
        student_fees_list: base_url + 'get-student-fee',
        get_library_url: base_url + 'get-library-url',
        compose_circular_post: base_url + 'compose-circular-post',
        remove_eligible_student: base_url + 'remove-eligible-student',
        faculty_subject_report: base_url + 'faculty-timetable-subject',
        single_subject_report: base_url + 'get-single-subject-report',
        get_single_mentor_csv: base_url + 'get-single-mentor-csv',
        past_username: base_url + 'past-username',
        set_student_pending_attendance: base_url + 'set-student-pending-attendance',
        upload_hod_attendance: base_url + 'upload-hod-attendance',
        placed_student_list: base_url + 'campus-placed-students',
        download_placement_report: base_url + 'download-placement-report',
        get_your_enrollment: base_url + 'know-new-user',
        get_sms_contents: base_url + 'get-sms-content',
        edit_sms_content: base_url + 'edit-sms-content',
        get_attendance_reason: base_url + 'get-attendance-comments',
        get_extra_att_list: base_url + 'get-extra-attendance-records',
        update_extra_att_record: base_url + 'update-extra-attendance-record',
        get_session_students_att: base_url + 'get-all-students-attendance',
        send_sms_to_parents: base_url + 'send-attendance-sms',
        get_all_buses: base_url + 'get-all-buses',
        get_single_bus_route: base_url + 'get-single-bus-route',
        submit_bus_details: base_url + 'select-bus-route',
        my_bus_route: base_url + 'my-bus-route',
        mentor_select_bus_route: base_url + 'assign-bus-route',
        mentee_bus_route: base_url + 'user-bus-route',
        department_time_table_sessions: base_url + 'department-time-table-sessions',
        get_attendance_sms_report: base_url + 'get-attendance-sms-report',
        search_bus_stops: base_url + 'search-bus-stops',
        add_route_to_bus: base_url + 'add-route-to-bus',
        update_bus_details: base_url + 'update-bus-details',
        get_all_user_bus: base_url + 'get-all-users-bus',
        generate_csv_internal: base_url + 'generate-csv-internal',
        get_all_stops: base_url + 'get-all-stops',
        add_stop: base_url + 'add-stop',
        remove_stop: base_url + 'remove-stop',
        remove_bus_root: base_url + 'remove-route-to-bus',
        update_site_notice: base_url + 'update-site-notice',
        get_site_notice: base_url + 'get-site-notice',
        edit_route_to_bus: base_url + 'edit-route-to-bus',
        update_elective_subject: base_url + 'update-elective-subject',
        get_attendance_csv: base_url + 'get-student-csv',
        mark_student_interested: base_url + 'mark-student-interested',
        get_attendance_comments: base_url + 'get-admin-attendance-comments',
        add_attendance_comment: base_url + 'add-attendance-comment',
        delete_attendance_comment: base_url + 'delete-attendance-comment',

        get_grievance_category: base_url + 'get-grievance-category', //grievance category
        get_grievance_by_user: base_url + 'grievance-get-user', //grievance user
        get_grievance: base_url + 'grievance-get', //grievance user
        add_grievance: base_url + 'grievance-add', //grievance add
        update_grievance: base_url + 'grievance-update-status', //grievance update status
        export_grievance_csv: base_url + 'export-grievance-csv', //grievance update status
        back_up_msg: base_url + 'back-up-msg',

    };

}]);
